using System.Buffers.Binary;

namespace WoWBuddy.Core.Execution;

/// <summary>
/// Emits the small set of 32-bit x86 instructions the bot injects into the game client.
/// </summary>
/// <remarks>
/// <para>
/// The bot runs code on the game's own thread by writing machine code into the client and
/// arranging for the client to call it. That code is generated here rather than shipped as a
/// compiled native DLL, which keeps the whole project in one MIT-licensed C# repository with
/// no C++ toolchain, and — more importantly — makes the generated bytes testable. Every
/// method below has a golden test asserting its exact output, and those expectations were
/// produced by disassembling the bytes with <c>objdump -b binary -m i386 -M intel</c> and
/// checking the mnemonics, not by copying them from the implementation.
/// </para>
/// <para>
/// Only what is needed is implemented. This is not a general assembler, and it should not
/// grow into one: every instruction here is a thing the bot pokes into somebody else's
/// process, and a small set is a reviewable set.
/// </para>
/// <para>
/// All displacements are absolute addresses in the <em>target</em> process. Relative operands
/// (<see cref="Call"/>, <see cref="JumpRelative"/>) are computed against
/// <see cref="BaseAddress"/>, which must therefore be the address the code will actually live
/// at. Getting that wrong produces code that jumps into the middle of the client, so
/// <see cref="BaseAddress"/> is required up front rather than patched in later.
/// </para>
/// </remarks>
public sealed class X86Assembler
{
    private readonly List<byte> _bytes = [];
    private readonly Dictionary<string, int> _labels = [];
    private readonly List<(int Offset, string Label)> _pendingShortJumps = [];

    /// <summary>Creates an assembler for code that will be placed at <paramref name="baseAddress"/>.</summary>
    public X86Assembler(nint baseAddress)
    {
        BaseAddress = baseAddress;
    }

    /// <summary>Address in the target process where the emitted code will live.</summary>
    public nint BaseAddress { get; }

    /// <summary>Number of bytes emitted so far.</summary>
    public int Length => _bytes.Count;

    /// <summary>Address the next emitted byte will occupy in the target process.</summary>
    public nint CurrentAddress => BaseAddress + _bytes.Count;

    /// <summary>Push all general-purpose registers. <c>pushad</c>.</summary>
    public X86Assembler PushAllRegisters() => Emit(0x60);

    /// <summary>Pop all general-purpose registers. <c>popad</c>.</summary>
    public X86Assembler PopAllRegisters() => Emit(0x61);

    /// <summary>Push the flags register. <c>pushfd</c>.</summary>
    public X86Assembler PushFlags() => Emit(0x9C);

    /// <summary>Pop the flags register. <c>popfd</c>.</summary>
    public X86Assembler PopFlags() => Emit(0x9D);

    /// <summary>Return. <c>ret</c>.</summary>
    public X86Assembler Return() => Emit(0xC3);

    /// <summary>Push an immediate 32-bit value. <c>push imm32</c>.</summary>
    public X86Assembler PushImmediate(uint value)
    {
        Emit(0x68);
        return EmitUInt32(value);
    }

    /// <summary>Push the 32-bit value stored at an absolute address. <c>push dword ptr [addr]</c>.</summary>
    public X86Assembler PushFromMemory(nint address)
    {
        Emit(0xFF, 0x35);
        return EmitAddress(address);
    }

    /// <summary>Load an immediate into eax. <c>mov eax, imm32</c>.</summary>
    public X86Assembler MoveEaxImmediate(uint value)
    {
        Emit(0xB8);
        return EmitUInt32(value);
    }

    /// <summary>Load an immediate into ecx, for thiscall targets. <c>mov ecx, imm32</c>.</summary>
    public X86Assembler MoveEcxImmediate(uint value)
    {
        Emit(0xB9);
        return EmitUInt32(value);
    }

    /// <summary>Copy eax into ecx, for chaining a thiscall onto a previous call's result. <c>mov ecx, eax</c>.</summary>
    public X86Assembler MoveEcxFromEax() => Emit(0x89, 0xC1);

    /// <summary>Store an immediate into an absolute address. <c>mov dword ptr [addr], imm32</c>.</summary>
    public X86Assembler StoreImmediate(nint address, uint value)
    {
        Emit(0xC7, 0x05);
        EmitAddress(address);
        return EmitUInt32(value);
    }

    /// <summary>Store eax at an absolute address. <c>mov dword ptr [addr], eax</c>.</summary>
    public X86Assembler StoreEax(nint address)
    {
        Emit(0xA3);
        return EmitAddress(address);
    }

    /// <summary>Store edx at an absolute address, for the high half of a 64-bit return. <c>mov dword ptr [addr], edx</c>.</summary>
    public X86Assembler StoreEdx(nint address)
    {
        Emit(0x89, 0x15);
        return EmitAddress(address);
    }

    /// <summary>
    /// Pop the top of the x87 stack into an absolute address. <c>fstp dword ptr [addr]</c>.
    /// </summary>
    /// <remarks>
    /// Only emit this when the called function actually returns a float. x87 return values
    /// are left on the FPU stack, and a function that did not leave one there would have its
    /// caller's FPU state corrupted by a stray pop.
    /// </remarks>
    public X86Assembler StoreFloatFromFpuStack(nint address)
    {
        Emit(0xD9, 0x1D);
        return EmitAddress(address);
    }

    /// <summary>Increment the 32-bit value at an absolute address. <c>inc dword ptr [addr]</c>.</summary>
    public X86Assembler IncrementMemory(nint address)
    {
        Emit(0xFF, 0x05);
        return EmitAddress(address);
    }

    /// <summary>Compare the 32-bit value at an absolute address with a small immediate. <c>cmp dword ptr [addr], imm8</c>.</summary>
    public X86Assembler CompareMemoryWithImmediate(nint address, byte value)
    {
        Emit(0x83, 0x3D);
        EmitAddress(address);
        return Emit(value);
    }

    /// <summary>Call an absolute address. <c>mov eax, addr</c> then <c>call eax</c>.</summary>
    /// <remarks>
    /// Via eax rather than a relative call so that the emitted bytes do not depend on where
    /// this code ends up. Clobbers eax, which is fine: eax is the return register and every
    /// caller here either stores it immediately or does not care.
    /// </remarks>
    public X86Assembler CallAbsolute(nint address)
    {
        MoveEaxImmediate((uint)address);
        return Emit(0xFF, 0xD0);
    }

    /// <summary>Call an address relative to this code's own position. <c>call rel32</c>.</summary>
    public X86Assembler CallRelative(nint target)
    {
        Emit(0xE8);
        // rel32 is measured from the instruction after the operand.
        return EmitUInt32((uint)(target - (CurrentAddress + 4)));
    }

    /// <summary>Jump through a pointer held at an absolute address. <c>jmp dword ptr [addr]</c>.</summary>
    /// <remarks>
    /// The way the hook hands control back to the real function. An indirect jump clobbers no
    /// register, which matters because it runs after <c>popad</c> has restored the client's
    /// own register state.
    /// </remarks>
    public X86Assembler JumpIndirect(nint pointerAddress)
    {
        Emit(0xFF, 0x25);
        return EmitAddress(pointerAddress);
    }

    /// <summary>Adjust the stack pointer, to clean up after a cdecl call. <c>add esp, imm8</c>.</summary>
    public X86Assembler AddToStackPointer(byte bytes)
    {
        if (bytes == 0)
        {
            return this;
        }

        return Emit(0x83, 0xC4, bytes);
    }

    /// <summary>Jump if not equal, to a label defined by <see cref="MarkLabel"/>. <c>jne rel8</c>.</summary>
    /// <remarks>
    /// Short form only: every branch in the generated stub spans a few dozen bytes at most.
    /// A target further than 127 bytes away is a sign the stub has grown beyond what it
    /// should be, so <see cref="MarkLabel"/> throws rather than silently widening it.
    /// </remarks>
    public X86Assembler JumpIfNotEqual(string label)
    {
        Emit(0x75);
        _pendingShortJumps.Add((_bytes.Count, label));
        return Emit(0x00);
    }

    /// <summary>Defines the target of a forward short jump.</summary>
    public X86Assembler MarkLabel(string label)
    {
        _labels[label] = _bytes.Count;
        return this;
    }

    /// <summary>Emits raw bytes verbatim.</summary>
    public X86Assembler Raw(params byte[] bytes)
    {
        _bytes.AddRange(bytes);
        return this;
    }

    /// <summary>
    /// Resolves pending jumps and returns the finished machine code.
    /// </summary>
    /// <exception cref="InvalidOperationException">
    /// A jump referenced a label that was never marked, or the branch is too far for its
    /// short encoding.
    /// </exception>
    public byte[] ToArray()
    {
        byte[] code = _bytes.ToArray();

        foreach ((int offset, string label) in _pendingShortJumps)
        {
            if (!_labels.TryGetValue(label, out int target))
            {
                throw new InvalidOperationException($"Jump to undefined label '{label}'.");
            }

            int displacement = target - (offset + 1);
            if (displacement is < sbyte.MinValue or > sbyte.MaxValue)
            {
                throw new InvalidOperationException(
                    $"Jump to '{label}' is {displacement} bytes away, which does not fit a short branch. " +
                    "The generated stub is not meant to be large enough for this to happen.");
            }

            code[offset] = unchecked((byte)(sbyte)displacement);
        }

        return code;
    }

    private X86Assembler Emit(params byte[] bytes)
    {
        _bytes.AddRange(bytes);
        return this;
    }

    private X86Assembler EmitUInt32(uint value)
    {
        Span<byte> buffer = stackalloc byte[4];
        BinaryPrimitives.WriteUInt32LittleEndian(buffer, value);
        _bytes.AddRange(buffer);
        return this;
    }

    private X86Assembler EmitAddress(nint address) => EmitUInt32((uint)address);
}
