<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>WoWBuddy.Profiles</RootNamespace>
    <AssemblyName>WoWBuddy.Profiles</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common\WoWBuddy.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serilog" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="WoWBuddy.Profiles.Tests" />
  </ItemGroup>
</Project>
