<Project>

  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningLevel>7</WarningLevel>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AnalysisLevel>latest</AnalysisLevel>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <Product>WoWBuddy</Product>
    <Company>WoWBuddy contributors</Company>
    <Copyright>Copyright (c) 2026 WoWBuddy contributors</Copyright>
    <Version>0.9.0</Version>
    <RepositoryUrl>https://github.com/Bar3b0n3s/WoWBuddy</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

</Project>
