<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>WoWBuddy.Behavior</RootNamespace>
    <AssemblyName>WoWBuddy.Behavior</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\WoWBuddy.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="WoWBuddy.Behavior.Tests" />
  </ItemGroup>

</Project>
