using System.Buffers.Binary;

namespace WoWBuddy.Core.Tests.Fakes;

/// <summary>
/// Executes the exact instruction subset <c>X86Assembler</c> emits, against simulated memory.
/// </summary>
/// <remarks>
/// <para>
/// The golden tests prove the generated bytes disassemble to the intended instructions. This
/// proves those instructions then <em>do the intended thing</em>: that arguments land in the
/// right order, that the stack is balanced, that results are stored where the bot later looks
/// for them, and that the stub's handshake behaves as designed frame by frame.
/// </para>
/// <para>
/// It understands only what the assembler can produce. Anything else throws rather than being
/// skipped, so a new instruction cannot quietly escape this coverage: adding one to the
/// assembler forces it to be added here too.
/// </para>
/// <para>
/// This is not an x86 emulator and must not become one. It has no notion of segmentation,
/// paging or faults, and its "stack" is a list. What it models is the shape of the code the
/// bot injects, which is exactly what needs checking.
/// </para>
/// </remarks>
public sealed class X86Interpreter
{
    private readonly SimulatedClient _memory;
    private readonly Func<nint, IReadOnlyList<uint>, uint, CallOutcome> _callHandler;
    private readonly List<uint> _stack = [];

    private uint _eax;
    private uint _ecx;
    private uint _edx;
    private float _fpuTop;
    private bool _fpuHasValue;
    private bool _zeroFlag;

    /// <summary>Function addresses that were called, in order.</summary>
    public List<nint> CallLog { get; } = [];

    /// <summary>Maximum instructions to run before assuming the code is looping.</summary>
    public int InstructionLimit { get; init; } = 10_000;

    /// <param name="memory">Memory the code reads and writes.</param>
    /// <param name="callHandler">
    /// Stands in for the client's own functions. Receives the target address, the arguments
    /// found on the simulated stack, and the current ecx, and returns what the function would
    /// have left in eax, edx and on the FPU stack.
    /// </param>
    public X86Interpreter(
        SimulatedClient memory,
        Func<nint, IReadOnlyList<uint>, uint, CallOutcome> callHandler)
    {
        _memory = memory;
        _callHandler = callHandler;
    }

    /// <summary>Runs code starting at <paramref name="address"/> until it returns or jumps away.</summary>
    /// <returns>The indirect-jump target that ended execution, or 0 if it ended with a return.</returns>
    public nint Run(nint address)
    {
        nint ip = address;
        int executed = 0;
        // A `call rel32` pushes a return address the interpreter models with this stack.
        var returnStack = new Stack<nint>();

        while (true)
        {
            if (++executed > InstructionLimit)
            {
                throw new InvalidOperationException(
                    $"Executed {InstructionLimit} instructions without terminating; the generated code loops.");
            }

            byte opcode = ReadByte(ip);

            switch (opcode)
            {
                case 0x60: // pusha
                case 0x61: // popa
                case 0x9C: // pushf
                case 0x9D: // popf
                    ip += 1;
                    break;

                case 0xC3: // ret
                    if (returnStack.Count == 0)
                    {
                        return 0;
                    }

                    ip = returnStack.Pop();
                    break;

                case 0x68: // push imm32
                    _stack.Add(ReadUInt32(ip + 1));
                    ip += 5;
                    break;

                case 0xB8: // mov eax, imm32
                    _eax = ReadUInt32(ip + 1);
                    ip += 5;
                    break;

                case 0xB9: // mov ecx, imm32
                    _ecx = ReadUInt32(ip + 1);
                    ip += 5;
                    break;

                case 0xA3: // mov [disp32], eax
                    WriteUInt32((nint)ReadUInt32(ip + 1), _eax);
                    ip += 5;
                    break;

                case 0xE8: // call rel32
                    {
                        nint target = ip + 5 + (int)ReadUInt32(ip + 1);
                        returnStack.Push(ip + 5);
                        ip = target;
                        break;
                    }

                case 0x75: // jne rel8
                    {
                        sbyte displacement = (sbyte)ReadByte(ip + 1);
                        ip += 2;
                        if (!_zeroFlag)
                        {
                            ip += displacement;
                        }

                        break;
                    }

                case 0x89: // mov ecx, eax  |  mov [disp32], edx
                    {
                        byte modrm = ReadByte(ip + 1);
                        if (modrm == 0xC1)
                        {
                            _ecx = _eax;
                            ip += 2;
                        }
                        else if (modrm == 0x15)
                        {
                            WriteUInt32((nint)ReadUInt32(ip + 2), _edx);
                            ip += 6;
                        }
                        else
                        {
                            throw Unsupported(ip, opcode, modrm);
                        }

                        break;
                    }

                case 0xC7: // mov dword [disp32], imm32
                    {
                        byte modrm = ReadByte(ip + 1);
                        if (modrm != 0x05)
                        {
                            throw Unsupported(ip, opcode, modrm);
                        }

                        WriteUInt32((nint)ReadUInt32(ip + 2), ReadUInt32(ip + 6));
                        ip += 10;
                        break;
                    }

                case 0x83: // cmp dword [disp32], imm8  |  add esp, imm8
                    {
                        byte modrm = ReadByte(ip + 1);
                        if (modrm == 0x3D)
                        {
                            uint value = ReadUInt32Memory((nint)ReadUInt32(ip + 2));
                            _zeroFlag = value == ReadByte(ip + 6);
                            ip += 7;
                        }
                        else if (modrm == 0xC4)
                        {
                            int slots = ReadByte(ip + 2) / 4;
                            for (int i = 0; i < slots && _stack.Count > 0; i++)
                            {
                                _stack.RemoveAt(_stack.Count - 1);
                            }

                            ip += 3;
                        }
                        else
                        {
                            throw Unsupported(ip, opcode, modrm);
                        }

                        break;
                    }

                case 0xD9: // fstp dword [disp32]
                    {
                        byte modrm = ReadByte(ip + 1);
                        if (modrm != 0x1D)
                        {
                            throw Unsupported(ip, opcode, modrm);
                        }

                        if (!_fpuHasValue)
                        {
                            throw new InvalidOperationException(
                                "fstp executed with nothing on the FPU stack. A call was declared as " +
                                "returning a float when it does not, which would corrupt the client's FPU state.");
                        }

                        _memory.WriteSingle((nint)ReadUInt32(ip + 2), _fpuTop);
                        _fpuHasValue = false;
                        ip += 6;
                        break;
                    }

                case 0xFF:
                    {
                        byte modrm = ReadByte(ip + 1);
                        switch (modrm)
                        {
                            case 0xD0: // call eax
                                PerformCall((nint)_eax);
                                ip += 2;
                                break;

                            case 0x05: // inc dword [disp32]
                                {
                                    nint target = (nint)ReadUInt32(ip + 2);
                                    WriteUInt32(target, ReadUInt32Memory(target) + 1);
                                    ip += 6;
                                    break;
                                }

                            case 0x35: // push dword [disp32]
                                _stack.Add(ReadUInt32Memory((nint)ReadUInt32(ip + 2)));
                                ip += 6;
                                break;

                            case 0x25: // jmp dword [disp32] - hands control to the real function
                                return (nint)ReadUInt32Memory((nint)ReadUInt32(ip + 2));

                            default:
                                throw Unsupported(ip, opcode, modrm);
                        }

                        break;
                    }

                default:
                    throw Unsupported(ip, opcode, 0);
            }
        }
    }

    private void PerformCall(nint function)
    {
        CallLog.Add(function);

        // The list grows with each push, so its last entry is the most recent push and
        // therefore sits at the lowest stack address: the callee's first argument. Reversing
        // gives the arguments in the order the called function declares them.
        uint[] arguments = Enumerable.Reverse(_stack).ToArray();
        CallOutcome outcome = _callHandler(function, arguments, _ecx);

        _eax = outcome.Eax;
        _edx = outcome.Edx;

        if (outcome.FloatResult is { } value)
        {
            _fpuTop = value;
            _fpuHasValue = true;
        }

        // A callee that cleans up its own stack has consumed the arguments by the time it
        // returns; a cdecl callee has not, and the caller's `add esp` will do it.
        if (outcome.CalleeCleansStack)
        {
            _stack.Clear();
        }
    }

    /// <summary>
    /// Values still on the simulated stack, for checking that a call balanced it. Ordered
    /// as the callee would see them: lowest address first.
    /// </summary>
    public IReadOnlyList<uint> RemainingStack => Enumerable.Reverse(_stack).ToList();

    private static InvalidOperationException Unsupported(nint ip, byte opcode, byte modrm) =>
        new($"Unsupported instruction at 0x{ip:X8}: opcode 0x{opcode:X2}, modrm 0x{modrm:X2}. " +
            "The interpreter must understand everything X86Assembler can emit.");

    private byte ReadByte(nint address)
    {
        Span<byte> buffer = stackalloc byte[1];
        if (!_memory.TryReadBytes(address, buffer))
        {
            throw new InvalidOperationException($"Executed unmapped memory at 0x{address:X8}.");
        }

        return buffer[0];
    }

    private uint ReadUInt32(nint address)
    {
        Span<byte> buffer = stackalloc byte[4];
        if (!_memory.TryReadBytes(address, buffer))
        {
            throw new InvalidOperationException($"Read unmapped code at 0x{address:X8}.");
        }

        return BinaryPrimitives.ReadUInt32LittleEndian(buffer);
    }

    private uint ReadUInt32Memory(nint address)
    {
        Span<byte> buffer = stackalloc byte[4];
        return _memory.TryReadBytes(address, buffer)
            ? BinaryPrimitives.ReadUInt32LittleEndian(buffer)
            : 0u;
    }

    private void WriteUInt32(nint address, uint value) => _memory.WriteUInt32(address, value);
}

/// <summary>What a stand-in for a client function leaves behind.</summary>
/// <param name="Eax">The 32-bit return value.</param>
/// <param name="Edx">The high half of a 64-bit return value.</param>
/// <param name="FloatResult">A value to leave on the FPU stack, for functions returning float.</param>
/// <param name="CalleeCleansStack">True for stdcall and thiscall targets.</param>
public readonly record struct CallOutcome(
    uint Eax = 0,
    uint Edx = 0,
    float? FloatResult = null,
    bool CalleeCleansStack = false);
