<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>WoWBuddy.Core</RootNamespace>
    <AssemblyName>WoWBuddy.Core</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\WoWBuddy.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="WoWBuddy.Core.Tests" />
  </ItemGroup>

</Project>
