<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>WoWBuddy.Navigation.Tests</RootNamespace>
    <AssemblyName>WoWBuddy.Navigation.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Common\WoWBuddy.Common.csproj" />
    <ProjectReference Include="..\..\src\Core\WoWBuddy.Core.csproj" />
    <ProjectReference Include="..\..\src\Navigation\WoWBuddy.Navigation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

</Project>
