using WoWBuddy.GameApi.Enums;

namespace WoWBuddy.CombatRoutines.Routines;

/// <summary>
/// Fury Warrior.
/// </summary>
/// <remarks>
/// <para>
/// The melee case. Rage is generated by fighting and decays out of combat, so there is no
/// resting for power and no opener that costs any: the pull is a charge, which generates rage
/// rather than spending it.
/// </para>
/// <para>
/// Spell names are the client's English names. Rotations are ordinary data and are meant to be
/// edited; the priorities here are the conventional Wrath ones rather than anything squeezed
/// out of a simulator.
/// </para>
/// </remarks>
public sealed class FuryWarrior : RoutineBase
{
    /// <inheritdoc />
    public override string Name => "Fury Warrior";

    /// <inheritdoc />
    public override WoWClass Class => WoWClass.Warrior;

    /// <summary>Charge reaches this far, and is how the fight starts.</summary>
    public override float PullRange => 20f;

    /// <inheritdoc />
    public override bool UsesDrinkablePower => false;

    /// <inheritdoc />
    protected override Rotation BuffRotation { get; } = new Rotation()
        .Cast("Battle Shout",
            c => !c.HasAura(c.Me, "Battle Shout"),
            onSelf: true,
            description: "keep the shout up out of combat");

    /// <inheritdoc />
    protected override Rotation PullRotation { get; } = new Rotation()
        .Cast("Charge", description: "closes the gap and generates rage")
        .Cast("Heroic Throw", description: "when charge is on cooldown");

    /// <inheritdoc />
    protected override Rotation CombatRotation { get; } = new Rotation()
        .Cast("Victory Rush",
            c => c.Me.HealthPercent < 90d,
            description: "free heal after a kill, taken when it is worth something")
        .Cast("Bloodthirst", description: "main rage dump")
        .Cast("Whirlwind",
            c => c.EnemiesInMelee >= 1,
            description: "hits everything in melee")
        .Cast("Slam",
            c => c.HasAura(c.Me, "Bloodsurge"),
            description: "only when the proc makes it instant")
        .Cast("Execute",
            c => c.Target is { HealthPercent: < 20d },
            description: "finisher")
        .Cast("Heroic Strike",
            c => c.Me.Power > 50,
            description: "rage dump so nothing is wasted");
}
